"""
data_collection.py
--------------------
Person 1 — Data/ML Owner
Secure Agentic Code Review — Dataset Collection

Collects real Pull Request data from the GitHub API for the fields required
by the project spec:
  PR ID, Repository, PR title, PR description, Author, Created date,
  Number of commits, Number of changed files, Additions, Deletions,
  Changed lines, Number of comments, Number of reviews, Review decision,
  Labels, Merged or not, Merge time, AI reviewer information,
  AI-generated code information.

REQUIREMENTS:
  pip install PyGithub pandas --break-system-packages
  export GITHUB_TOKEN=ghp_xxxxxxxxxxxx

USAGE:
  python data_collection.py --repos facebook/react microsoft/vscode \
      pytorch/pytorch pandas-dev/pandas vercel/next.js \
      --per-repo 300 --out ../../data/raw_prs.json
"""

import argparse
import json
import os
import re
import time
from github import Github, GithubException

# ---------------------------------------------------------------------------
# AI reviewer / AI-generated-code heuristics (extend as needed once you
# inspect real data — these are a reasonable starting point).
# ---------------------------------------------------------------------------
AI_REVIEWER_LOGINS = {
    "github-actions[bot]", "copilot", "copilot-pull-request-reviewer[bot]",
    "coderabbitai[bot]", "sourcery-ai[bot]", "codeium[bot]", "cursor[bot]",
    "greptile-apps[bot]", "graphite-app[bot]",
}

AI_CODE_KEYWORDS = re.compile(
    r"\b(generated by copilot|co-authored-by:\s*copilot|generated with (chatgpt|claude|cursor)|"
    r"ai[- ]generated|written by (chatgpt|copilot|claude))\b",
    re.IGNORECASE,
)


def is_ai_reviewer(login: str) -> bool:
    if not login:
        return False
    login_lower = login.lower()
    return login_lower in AI_REVIEWER_LOGINS or (
        "bot" in login_lower
        and any(k in login_lower for k in ["copilot", "coderabbit", "sourcery", "codeium", "cursor", "greptile"])
    )


def is_ai_generated_code(pr_title: str, pr_body: str, commit_messages: list) -> bool:
    text = " ".join([pr_title or "", pr_body or ""] + commit_messages)
    return bool(AI_CODE_KEYWORDS.search(text))


def fetch_repo_prs(gh: Github, repo_name: str, limit: int):
    repo = gh.get_repo(repo_name)
    records = []
    pulls = repo.get_pulls(state="all", sort="created", direction="desc")

    count = 0
    for pr in pulls:
        if count >= limit:
            break
        try:
            reviews = list(pr.get_reviews())
            review_comments = list(pr.get_review_comments())
            issue_comments = list(pr.get_issue_comments())
            commits = list(pr.get_commits())
            files = list(pr.get_files())
            labels = [l.name for l in pr.get_labels()]

            commit_messages = [c.commit.message for c in commits]
            reviewer_logins = [r.user.login if r.user else "" for r in reviews]
            review_decisions = [r.state for r in reviews]

            additions = pr.additions
            deletions = pr.deletions

            record = {
                "pr_id": pr.number,
                "repository": repo_name,
                "pr_title": pr.title,
                "pr_description": pr.body or "",
                "author": pr.user.login if pr.user else None,
                "created_date": pr.created_at.isoformat() if pr.created_at else None,
                "merged_date": pr.merged_at.isoformat() if pr.merged_at else None,
                "closed_date": pr.closed_at.isoformat() if pr.closed_at else None,
                "num_commits": len(commits),
                "num_changed_files": len(files),
                "additions": additions,
                "deletions": deletions,
                "changed_lines": additions + deletions,
                "num_comments": len(issue_comments) + len(review_comments),
                "num_reviews": len(reviews),
                "review_decisions": review_decisions,
                "num_reviewers": len(set(reviewer_logins)),
                "labels": labels,
                "merged": bool(pr.merged),
                "merge_time_hours": (
                    (pr.merged_at - pr.created_at).total_seconds() / 3600.0
                    if pr.merged_at and pr.created_at else None
                ),
                "ai_reviewer_present": any(is_ai_reviewer(u) for u in reviewer_logins),
                "ai_reviewer_names": [u for u in reviewer_logins if is_ai_reviewer(u)],
                "ai_code_present": is_ai_generated_code(pr.title, pr.body, commit_messages),
                "commit_messages": commit_messages[:10],
                "modified_files": [f.filename for f in files[:20]],
            }
            records.append(record)
            count += 1

        except GithubException as e:
            print(f"[warn] Skipping PR #{pr.number} in {repo_name}: {e}")
            continue

        if count % 25 == 0:
            print(f"  {repo_name}: fetched {count}/{limit} PRs...")
            time.sleep(1)

    return records


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--repos", nargs="+", required=True)
    parser.add_argument("--per-repo", type=int, default=300)
    parser.add_argument("--out", type=str, default="../../data/raw_prs.json")
    args = parser.parse_args()

    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        raise SystemExit("ERROR: set the GITHUB_TOKEN environment variable first.")

    gh = Github(token, per_page=100)

    all_records = []
    for repo_name in args.repos:
        print(f"Fetching {args.per_repo} PRs from {repo_name} ...")
        try:
            records = fetch_repo_prs(gh, repo_name, args.per_repo)
            all_records.extend(records)
        except GithubException as e:
            print(f"[error] Could not fetch {repo_name}: {e}")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        json.dump(all_records, f, indent=2, default=str)

    print(f"\nSaved {len(all_records)} raw PR records to {args.out}")


if __name__ == "__main__":
    main()
